name: McXyhjMMO
version: ${project.version}
main: mcxyhj.cn.knkiss.McXyhjMMO
api-version: 1.16
authors: [ Knkiss, Dnkiss ]
description: A RpgMMO For Minecraft From XYHJ
website: mcxyhj.cn

commands:
  xyhjmmo:
    description: 查看关于星夜幻境MMO插件的使用
    usage: /xyhjmmo
    aliases: mmo